---
kind: ClusterConfiguration
apiVersion: konvoy.mesosphere.io/v1alpha1
metadata:
  name: two-sigma-testing
  creationTimestamp: "2019-12-26T19:26:03.023482Z"
spec:
  kubernetes:
    version: 1.15.5
    controlPlane:
      controlPlaneEndpointOverride: "192.168.2.121:6443"
      certificate: {}
      keepalived:
        enabled: true
    networking:
      podSubnet: 172.17.0.0/16
      serviceSubnet: 10.0.0.0/18
      httpProxy: ""
      httpsProxy: ""
    cloudProvider:
      provider: none
    admissionPlugins:
      enabled:
      - NodeRestriction
      - AlwaysPullImages
      disabled: []
    preflightChecks:
      errorsToIgnore: []
  containerNetworking:
    calico:
      version: v3.8.2
  containerRuntime:
    containerd:
      version: 1.2.6
      configData:
        data: ""
        replace: false
  packageRepository:
    defaultRepositoryInstallationDisabled: false
  nodePools:
  - name: worker
    gpu:
      nvidia:
        enabled: false
  addons:
    configRepository: https://github.com/mesosphere/kubeaddons-configs
    configVersion: stable-1.15.5-2
    addonsList:
    - name: cert-manager
      enabled: true
    - name: dashboard
      enabled: true
    - name: dex
      enabled: true
    - name: dex-k8s-authenticator
      enabled: true
    - name: elasticsearch
      enabled: true
    - name: elasticsearchexporter
      enabled: true
    - name: fluentbit
      enabled: true
    - name: helm
      enabled: true
    - name: kibana
      enabled: true
    - name: kommander
      enabled: false
    - name: konvoyconfig
      enabled: true
    - name: localvolumeprovisioner
      enabled: false
    - name: metallb
      enabled: true
      values: |-
        configInline:
          address-pools:
          - name: default
            protocol: layer2
            addresses: [192.168.2.122-192.168.2.130]
    - name: opsportal
      enabled: true
    - name: prometheus
      enabled: true
    - name: prometheusadapter
      enabled: true
    - name: traefik
      enabled: true
    - name: traefik-forward-auth
      enabled: true
    - name: velero
      enabled: true
  version: v1.2.6

